//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmPJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalType
    {
        public AnimalType()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public int AnimalTypeId { get; set; }
        public string AnimalTypeName { get; set; }
        public string Sound { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
